#! /usr/env ruby -w


#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


# hint: Fibonacci F(n)=4F(n-3) + F(n-6)
# hint: E(n)=4E(n-1) + E(n-2)  E(1) = 2 ,E(2) = 8

def fibonacci(n = 100)
  a, b = 1,1
  n.times do
    printf("%d\n",a)
    a, b = b, a+b
  end
end

LIMIT = 4000000

def problem2
  e1,e2 = 2,8
  en = 4*e2 + e1
  sum = 2+8
  while en < LIMIT
    sum = en + sum
    e1,e2 = e2, en
    en = 4*e2 + e1
  end
  sum
end

puts problem2  